<a href="https://colab.research.google.com/github/DANGKHOIk22/data-science/blob/main/18_4_learning_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np

# TENSOR

In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector=torch.tensor([2,2])
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix=torch.tensor([[1,2],
                     [3,4]])
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
matrix[0]

tensor([1, 2])

# Random tensor

In [11]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9797, 0.1219, 0.2550, 0.1545],
        [0.3642, 0.6614, 0.3174, 0.4091],
        [0.0663, 0.1291, 0.5347, 0.3793]])

In [12]:
random_tensor.ndim

2

In [13]:
random_image_size=torch.rand((224,224,3))
random_image_size.shape,random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [14]:
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones=torch.ones(size=(4,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
zero.dtype

torch.float32

# Creating a range of tensors and tensors-like

3 big errors you'll run into with pytorch & DL

1. tensor is not right datatype
2. tensor is not right shape
3. tensor is on not right device

In [17]:
one_to_ten=torch.arange(start=0,end=10,step=2)

In [18]:
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [19]:
tensor=torch.tensor([1.,2.,3.],dtype=None,device=None,requires_grad=False)
tensor.dtype

torch.float32

In [20]:
tensor_16=tensor.type(torch.float16)

# Getting information from tensors

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in?

device - what device is the tensor stored on? (usually GPU or CPU)

In [21]:
random_tensor=torch.rand(3,4)
random_tensor.shape

torch.Size([3, 4])

In [22]:
random_tensor.size()

torch.Size([3, 4])

In [23]:
random_tensor.device

device(type='cpu')

# Manipulating tensors (tensor operations)

In [24]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [25]:
tensor*10

tensor([10, 20, 30])

In [26]:
torch.matmul(tensor,tensor)

tensor(14)

# Finding the min, max, mean, sum, etc (aggregation)

In [27]:
matrix=torch.arange(1,10)

In [28]:
torch.mean(matrix.type(torch.float32))

tensor(5.)

In [29]:
torch.sum(matrix),matrix.sum()

(tensor(45), tensor(45))

# Finding positional min and max

In [30]:
matrix.argmin()

tensor(0)

In [31]:
matrix.argmax()

tensor(8)

# Reshaping, stacking, squeezing, unsqueezing tensor

torch.reshape(input, shape)	Reshapes input to shape (if compatible)

torch.view(shape)	Returns a view of the original tensor in a different shape but shares the memory data as the original tensor.

torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.

torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.

torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims but shares the memory data as the original tensor.

In [32]:
x=torch.arange(0,10,2)
x.reshape(1,5)

tensor([[0, 2, 4, 6, 8]])

In [33]:
z=x.view(1,5)
z[:,2]=12
x

tensor([ 0,  2, 12,  6,  8])

In [34]:
torch.stack([x,x,x,x],dim=0)

tensor([[ 0,  2, 12,  6,  8],
        [ 0,  2, 12,  6,  8],
        [ 0,  2, 12,  6,  8],
        [ 0,  2, 12,  6,  8]])

In [35]:
torch.vstack([x,x,x,x])

tensor([[ 0,  2, 12,  6,  8],
        [ 0,  2, 12,  6,  8],
        [ 0,  2, 12,  6,  8],
        [ 0,  2, 12,  6,  8]])

In [36]:
torch.hstack([x,x,x,x])

tensor([ 0,  2, 12,  6,  8,  0,  2, 12,  6,  8,  0,  2, 12,  6,  8,  0,  2, 12,
         6,  8])

In [37]:
zero=torch.zeros(1,1,3)
zero=zero.squeeze()

In [38]:
zero.shape

torch.Size([3])

In [39]:
zero=zero.unsqueeze(dim=0)
zero.shape

torch.Size([1, 3])

In [40]:
x_original=torch.rand(size=(224,224,3))
x_pe=x_original.permute(2,0,1) # shift positional axis

In [41]:
x_original[0,0,0]=33
x_pe[0,0,0]

tensor(33.)

# Indexing (selecting data from tensors)

In [42]:
x=torch.arange(1,10)
x=x.reshape(1,3,3)

In [43]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
x[0,0]

tensor([1, 2, 3])

In [45]:
x[0,0,0].item()

1

In [46]:
x[:,:,1]

tensor([[2, 5, 8]])

In [47]:
x[0,2,2]

tensor(9)

In [48]:
x[0,:,2]

tensor([3, 6, 9])

# pytorch and numpy

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [49]:
import numpy as np
array=np.arange(0,10)
tensor=torch.from_numpy(array)

Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

In [50]:
array=array+1
array,tensor

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

# Reproducibility

In [51]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

# Getting PyTorch to run on the GPU

In [52]:
# Check for GPU
torch.cuda.is_available()

True

In [53]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'


Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across all GPUs).

In [54]:
torch.cuda.device_count()

1

# Putting tensors (and models) on the GPU

In [55]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

#  Moving tensors back to the CPU

In [56]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [57]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [58]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Exercise

In [61]:
A=torch.rand(size=(7,7))

In [62]:
B=torch.rand(size=(7,7))
A@B.T

tensor([[1.7076, 1.8826, 1.1483, 2.2462, 1.8776, 1.3752, 1.4623],
        [1.1082, 0.9401, 0.8433, 1.2373, 1.0883, 0.9750, 0.8197],
        [1.2293, 1.6033, 1.2308, 2.1269, 1.8825, 1.2372, 0.8286],
        [1.0241, 0.9660, 0.8691, 1.3800, 1.0965, 1.1705, 1.1153],
        [1.3169, 1.5830, 1.2840, 2.1803, 1.6294, 1.4803, 1.3084],
        [2.5243, 2.1800, 1.4394, 2.5405, 2.2355, 1.9520, 2.1277],
        [1.6868, 1.8788, 1.6629, 2.5312, 2.2523, 1.7354, 1.3013]])

In [64]:
torch.manual_seed(0)
B=torch.rand(size=(7,7))
A@B.T

tensor([[1.5628, 1.7665, 1.6012, 2.1706, 0.8454, 1.2318, 1.2685],
        [0.8029, 0.6490, 0.9981, 1.1764, 0.8510, 1.1275, 0.8638],
        [1.2734, 1.0155, 1.3630, 1.4816, 0.7154, 1.5502, 1.4960],
        [0.6571, 1.4104, 1.1883, 1.7737, 0.8236, 1.3598, 0.9107],
        [1.2475, 1.6478, 1.4078, 2.0119, 0.8120, 1.6300, 1.4380],
        [1.6568, 1.8957, 2.3531, 2.7087, 1.7913, 2.1838, 1.3954],
        [1.4086, 1.5421, 1.7349, 2.4403, 0.9620, 2.1114, 1.7751]])

In [65]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [67]:
torch.manual_seed(1234)
A=torch.rand(size=(2,3))
B=torch.rand(size=(2,3))
A=A.to(device)
B=B.to(device)

In [71]:
C=A@B.T

In [73]:
torch.max(C)
torch.min(C)

tensor(0.3647, device='cuda:0')

In [75]:
torch.argmax(C)
torch.argmin(C)

tensor(0, device='cuda:0')

In [77]:
torch.manual_seed(7)
A=torch.rand(size=(1,1,1,10))
A.squeeze()

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])