In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
#data = pd.read_csv('iris_train.csv')

In [3]:
#w=np.array([0.1,0.1,1])
#b=5
b = 786.1811367994083
w = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [4]:
#x=data.drop('FINAL',axis='columns')
#y=data.FINAL
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y = np.array([460, 232, 178])

In [5]:
scaler = StandardScaler()
x = scaler.fit_transform(x_train)

In [6]:
print(x)

[[ 1.26311506  1.33630621 -0.70710678  1.22474487]
 [-0.08073519 -0.26726124  1.41421356  0.        ]
 [-1.18237987 -1.06904497 -0.70710678 -1.22474487]]


In [7]:
#y=y.to_numpy()

In [8]:
#x=x.to_numpy()

In [9]:
t=np.dot(w,x[0])
print(t)

30.92715325268737


In [10]:
print(y)

[460 232 178]


In [11]:
def loss_function(w,b,x,y):
    n=x.shape[0]
    j=0
    for i in range(len(x)):
        j+=(np.dot(w,x[i])+b-y[i])**2
    j=j/(2*n)
    return j

In [12]:
def gradient_function(w,b,x,y):
    n=len(x)
    w_gr=np.zeros((4,))
    b_gr=0.
    for i in range(len(x)):
        w_gr+=(np.dot(w,x[i])+b-y[i])*x[i]
        b_gr+=(np.dot(w,x[i])+b-y[i])
    w_gr/=len(x)
    b_gr/=len(x)
    return w_gr,b_gr

In [13]:
def gradient_descent(w,b,x,y):
    alpha =5.0e-7
    for i in range(len(x)):
        w_gr,b_gr=gradient_function(w,b,x,y)
        w-=alpha*w_gr
        b-=alpha*b_gr
    return w,b

In [14]:
w_final,b_final=gradient_descent(w,b,x,y)
n=len(x)
f=np.zeros((3,3))
for i in range(n):
    f[i]=np.dot(w_final,x_train[i]) + b_final
   # print(f"prediction: {np.dot(w_final,x_train[i]) + b_final:0.2f}, target value: {y[i]}")
    #f=np.dot(w_final,x[i])+b_final

In [15]:
#xx=np.array([2104, 5, 1, 45])
#print(np.dot(w_final,xx)+b_final)

In [16]:
reg=linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression()

In [17]:
reg.predict([[2104, 5, 1, 45]])

array([82162.70533326])

In [18]:
reg.coef_

array([ 38.05161505,  41.54327451, -30.98894656,  36.34177447])

In [19]:
sgdr = SGDRegressor(max_iter=1000)
sgdr.fit(x, y)

c:\Users\DANGKHOI\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1503: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor()

In [20]:
print(sgdr.predict([[2104, 5, 1, 45]]))

[82172.63186032]
